name: Deploy

on:
  push:
    branches:
      - deploy-to-rush-admin

jobs:
  send_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send Webhook
        env:
          SECRET: ${{ secrets.DEPLOY_WEBHOOK_SECRET }}
        run: |
          BODY='{}'
          TIMESTAMP=$(date +%s)
          SIGNATURE=$(echo -n "$TIMESTAMP$BODY" | openssl dgst -sha256 -hmac "$SECRET" | cut -d " " -f2)
          curl -X POST https://whatstherush.earth/deploy/python-deployer \
              -H "Content-Type: application/json" \
              -H "X-Timestamp: $TIMESTAMP" \
              -H "X-Signature: $SIGNATURE" \
              -d "$BODY"

